---
title: "Tool Errors"
description: "Documentation for the different types of tool errors in the Arcade AI Tool SDK"
---

# Tool errors in Arcade AI

When working with Arcade AI's Tool SDK, you may encounter various types of errors. This guide will help you understand and handle these errors effectively.

## Handling errors in your tools

In most cases, you don't need to raise errors explicitly in your tools. The `@tool` decorator takes care of proper error propagation and handling. When an unexpected error occurs during tool execution, Arcade AI's `ToolExecutor` and `@tool` decorator will raise a `ToolExecutionError` with the necessary context and traceback information.

However, if you want to retry the tool call with additional content to improve the tool call's input parameters, you can raise a [RetryableToolError](/guides/toolsdk/retryable-tool-error) within the tool.

## Common error scenarios

Let's explore some common error scenarios you might encounter:

### 1. Output type mismatch

This occurs when the expected output type of a tool does not match the actual output type when executed.

```json
{
  "name": "tool_call_error",
  "message": "tool call failed - Example.Hello failed: Failed to
  serialize tool output"
}
```

For example, the following tool will raise the above error:

```python
from typing import Annotated
from arcade.sdk import tool

@tool
def hello(name: Annotated[str, "The name of the friend to greet"]) -> str:
  """
  Says hello to a friend
  """
  return ["hello", name]
```

### 2. Input parameter type error

This occurs when the input parameter of a tool is of an unsupported type.

```
Type error encountered while adding tool list_org_repositories from
arcade_github.tools.repositories. Reason: issubclass() arg 1 must be a class
```

For example, the following tool will raise the above error because the tool input parameter is of an unsupported type:

```python
from typing import Annotated
from arcade.sdk import tool

@tool
def hello(names: Annotated[tuple[str, str, str], "The names of the friends to greet"]) -> str:
  """
  Says hello to a list of friends
  """
  return f"Hello, {names[0]}, {names[1]}, and {names[2]}!"
```

### 3. Unexpected HTTP error during tool execution

This occurs when the tool makes an HTTP request and receives a non-2xx response. Specifically for the example below, the tool did not have a valid authorization token to access the private repository.

```json
{
  "name": "tool_call_error",
  "message": "tool call failed - Github.ListOrgRepositories failed: Error accessing 'https://api.github.com/orgs/a-private-org/repos': Failed to process request. Status code: 401"
}
```

## RetryableToolError in Arcade AI

Sometimes you may want to retry a tool call with additional context to improve the tool call's input parameters predicted by the LLM and try again. You can do this by raising a `RetryableToolError` within the tool.

### Understanding RetryableToolError

Raising the `RetryableToolError` is useful when you want to retry the tool call and give the LLM that is generating the tool call's input parameters additional context to improve the parameters for the next tool call.

### When to Use RetryableToolError

A RetryableToolError should be raised from within a tool if additional prompt content would likely improve the tool call outcome.

### Example: Sending a Direct Message in Slack

Below is an example of a tool that sends a direct message to a user in Slack:

1. If the specified user is not found, the tool retrieves a list of all valid inputs for the `user_name` parameter.
2. The tool then raises a `RetryableToolError` with the list of valid inputs.
3. This allows the LLM to generate a valid input for the `user_name` parameter in the next tool call iteration.

```python file=<rootDir>/examples/code/guides/toolsdk/retryable_tool_error_example.py {44-49}

```
